name: "Deploy to Hacklas"

on:
  push:
    branches: ["hacklas"]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    permissions:
      contents: write
      pages: write
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v7

      - name: Setup Node
        uses: actions/setup-node@v5
        with:
          node-version-file: .nvmrc
          cache: npm

      - name: Install
        run: npm ci

      - name: Production Build
        if: success()
        run: npm run build

      - name: Upload artifact
        if: github.event_name == 'push' && github.ref == 'refs/heads/hacklas'
        uses: actions/upload-pages-artifact@v5
        with:
          path: ./dist

  deploy:
    if: github.event_name == 'push' && github.ref == 'refs/heads/hacklas'
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
